[build]
builder = "nixpacks"
buildCommand = "NEXT_TELEMETRY_DISABLED=1 CI=true npm run build || npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 3 